/**
 * Created by whv2li8 on 27/04/2017.
 */
export class Refs{

    static list : string[] = [
    "Vincent Moenens",
          "Franky Vanhoutte",
          "Andy Lagaise",
          "Frank Dendievel",
          "Pascal Princen",
          "Pol Lavens",
          "Kristof Damman",
          "Marnic Moyaert	",
          "Stephane Vandendriessche",
          "Bert Schietgat",
          "Jirre Verledens",
          "Gerrit Descamps",
          "Renaat Deschuymere",
          "Franky Vanhoutte",
          "Philip Beernaert",
          "Vincent Moenens	",
          "Franky Vanhoutte",
          "Andy Lagaise",
          "Frank Dendievel",
          "Pascal Princen",
          "Pol Lavens",
          "Kristof Damman",
          "Marnic Moyaert",
          "Stephane Vandendriessche	",
          "Bert Schietgat",
          "Jirre Verledens",
          "Gerrit Descamps",
          "Renaat Deschuymere",
          "Andy Lagaise",
          "Philip Beernaert",
          "Vincent Moenens",
          "Franky Vanhoutte	",
          "Andy Lagaise",
          "Frank Dendievel",
          "Pascal Princen",
          "Pol Lavens",
          "Kristof Damman",
          "Marnic Moyaert",
          "Stephane Vandendriessche",
          "Bert Schietgat	",
          "Jirre Verledens",
          "Gerrit Descamps",
          "Renaat Deschuymere",
          "Frank Dendievel",
          "Philip Beernaert",
          "Vincent Moenens",
          "Franky Vanhoutte",
          "Andy Lagaise	",
          "Gerrit Descamps",
          "Renaat Deschuymere",
          "Stephane Vandendriessche",
          "Philip Beernaert",
          "Andy Lagaise",
          "Frank Dendievel",
          "Pascal Princen",
          "Pol Lavens	",
          "Frank Dendievel",
          "Pascal Princen",
          "Pol Lavens",
          "Kristof Damman",
          "Marnic Moyaert",
          "Stephane Vandendriessche",
          "Bert Schietgat",
          "Jirre Verledens	",
          "Philip Beernaert",
          "Frank Dendievel",
          "Pascal Princen",
          "Pol Lavens",
          "Kristof Damman",
          "Marnic Moyaert",
          "Stephane Vandendriessche",
          "Bert Schietgat	",
          "Kristof Damman",
          "Marnic Moyaert",
          "Stephane Vandendriessche",
          "Bert Schietgat",
          "Jirre Verledens",
          "Gerrit Descamps",
          "Renaat Deschuymere",
          "Frank Dendievel",
          "Kristof Damman",
          "Stephane Vandendriessche",
          "Marnic Moyaert",
          "Bert Schietgat",
          "Jirre Verledens",
          "Gerrit Descamps",
          "Renaat Deschuymere",
          "Dimitri Verthé",
          "Jirre Verledens",
          "Gerrit Descamps",
          "Renaat Deschuymere",
          "Dimitri Verthé",
          "Philip Beernaert",
          "Frank Dendievel",
          "Pascal Princen",
          "Pol Lavens	",
          "TBA",
          "Gerrit Descamps",
          "Renaat Deschuymere",
          "Marnic Moyaert",
          "Philip Beernaert",
          "Pascal Princen",
          "Pol Lavens",
          "Kristof Damman	",
          "Philip Beernaert",
          "Pascal Princen",
          "Pol Lavens",
          "Kristof Damman",
          "Marnic Moyaert",
          "Stephane Vandendriessche",
          "Bert Schietgat",
          "Jirre Verledens"
    ];

}
