/**
 * Created by whv2li8 on 27/04/2017.
 */

export class Refs{


    static list : string[] =
    ["Frank Dendievel","Boucquez S.","Gino Sandra","Kristof Damman","Wim Dubois","Pascal Princen","Stefaan Balcaen","Nicolas Keygnaert",
    "Frank Dendievel","Boucquez S.","Gino Sandra","Stephane Vandendriessche","Pol Lavens","Marnic Moyaert","Wim Dubois","Pascal P. ",
    "Frank Dendievel","Stephane Vandendriessche","Pol Lavens","Kristof Damman","Nicolas Keygnaert","Stefaan Balcaen","Marnic Moyaert","Wim Dubois",
    "Marnic Moyaert","Wim Dubois","Vincent Moenens","Stephane Vandendriessche","Pol Lavens","Kristof Damman","Pascal Princen","Nicolas Keygnaert",
    "Marnic Moyaert","Wim Dubois","Vincent Moenens","Stephane Vandendriessche","Pol Lavens","Kristof Damman","Pascal Princen","Nicolas Keygnaert",
    "Gino Sandra","Boucquez S.","Pascal Princen","Nicolas Keygnaert","Stefaan Balcaen","Kristof Damman","Stephane Vandendriessche","Pol Lavens",
    "Vincent Moenens","Gerrit Descamps","Eric Vanneste","Wim Dubois","Pascal Princen","Stephane Vandendriessche","Pol Lavens","Stefaan Balcaen",
    "Stefaan Balcaen","Vincent Moenens","Gerrit Descamps","Eric Vanneste","Boucquez S.","Nicolas Keygnaert","Marnic Moyaert","Kristof Damman",
    "Gerrit Descamps","Stephane Vandendriessche","Pol Lavens","Pascal Princen","Eric Vanneste","Vincent Moenens","Nicolas Keygnaert","Stefaan Balcaen",
    "Wim Dubois","Stefaan Balcaen","Nicolas Keygnaert","Kristof Damman","Marnic Moyaert","Vincent Moenens","Eric Vanneste","Gerrit Descamps",
    "Stephane Vandendriessche","Stefaan Balcaen","Gerrit Descamps","Eric Vanneste","Vincent Moenens","Pascal Princen","Wim Dubois","Kristof Damman",
    "Marnic Moyaert","Kristof Damman","Wim Dubois","Gerrit Descamps","Eric Vanneste","Vincent Moenens","Pascal Princen","Nicolas Keygnaert"]
;



    /*static list : string[] = [
    "Vincent Moenens",
          "Franky Vanhoutte",
          "Andy Lagaise",
          "Frank Dendievel",
          "Pascal Princen",
          "Pol Lavens",
          "Kristof Damman",
          "Marnic Moyaert	",
          "Stephane Vandendriessche",
          "Bert Schietgat",
          "Jirre Verledens",
          "Gerrit Descamps",
          "Renaat Deschuymere",
          "Franky Vanhoutte",
          "Philip Beernaert",
          "Vincent Moenens	",
          "Franky Vanhoutte",
          "Andy Lagaise",
          "Frank Dendievel",
          "Pascal Princen",
          "Pol Lavens",
          "Kristof Damman",
          "Marnic Moyaert",
          "Stephane Vandendriessche	",
          "Bert Schietgat",
          "Jirre Verledens",
          "Gerrit Descamps",
          "Renaat Deschuymere",
          "Andy Lagaise",
          "Philip Beernaert",
          "Vincent Moenens",
          "Franky Vanhoutte	",
          "Andy Lagaise",
          "Frank Dendievel",
          "Pascal Princen",
          "Pol Lavens",
          "Kristof Damman",
          "Marnic Moyaert",
          "Stephane Vandendriessche",
          "Bert Schietgat	",
          "Jirre Verledens",
          "Gerrit Descamps",
          "Renaat Deschuymere",
          "Frank Dendievel",
          "Philip Beernaert",
          "Vincent Moenens",
          "Franky Vanhoutte",
          "Andy Lagaise	",
          "Gerrit Descamps",
          "Renaat Deschuymere",
          "Stephane Vandendriessche",
          "Philip Beernaert",
          "Andy Lagaise",
          "Frank Dendievel",
          "Pascal Princen",
          "Pol Lavens	",
          "Frank Dendievel",
          "Pascal Princen",
          "Pol Lavens",
          "Kristof Damman",
          "Marnic Moyaert",
          "Stephane Vandendriessche",
          "Bert Schietgat",
          "Jirre Verledens	",
          "Philip Beernaert",
          "Frank Dendievel",
          "Pascal Princen",
          "Pol Lavens",
          "Kristof Damman",
          "Marnic Moyaert",
          "Stephane Vandendriessche",
          "Bert Schietgat	",
          "Kristof Damman",
          "Marnic Moyaert",
          "Stephane Vandendriessche",
          "Bert Schietgat",
          "Jirre Verledens",
          "Gerrit Descamps",
          "Renaat Deschuymere",
          "Frank Dendievel",
          "Kristof Damman",
          "Stephane Vandendriessche",
          "Marnic Moyaert",
          "Bert Schietgat",
          "Jirre Verledens",
          "Gerrit Descamps",
          "Renaat Deschuymere",
          "Dimitri Verthé",
          "Jirre Verledens",
          "Gerrit Descamps",
          "Renaat Deschuymere",
          "Dimitri Verthé",
          "Philip Beernaert",
          "Frank Dendievel",
          "Pascal Princen",
          "Pol Lavens	",
          "TBA",
          "Gerrit Descamps",
          "Renaat Deschuymere",
          "Marnic Moyaert",
          "Philip Beernaert",
          "Pascal Princen",
          "Pol Lavens",
          "Kristof Damman	",
          "Philip Beernaert",
          "Pascal Princen",
          "Pol Lavens",
          "Kristof Damman",
          "Marnic Moyaert",
          "Stephane Vandendriessche",
          "Bert Schietgat",
          "Jirre Verledens"
    ];*/

}
